HNHN/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HNHB.Models.Entities;// gì mà HNHB nữa? Moi dau ten project sai =)) copy pasr thì cũng phải để ý đầy đủ chứ
//làm lại đi, bây giờ namespace tùm lum hết rồi, nếu biết chỗ sửa thì sửa, dùng find replace all thử, gio doi lai ten het ah uh. 
//bây giờ mày đang dùng 2 cái HNHB do mày copy qua, còn cái HNHB là do code máy tự sinh.
//đáng lẽ nó phải là 1, giớ lam sao, đổi HNHB thành HNHB
// replace all
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
namespace HNHB.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
          // Get database context
        Entities db = new Entities();
        // Get data for homepage
        public ActionResult Index()
        {
            //List<int> CateList = new List<int> { 1, 2, 8, 10 };
            //List<Place> model = db.Places.Where(p => p.IsActive == true && p.IsApproved == true && CateList.Contains(p.SubCategory.CategoryId)).OrderBy(p => p.RateValue).ThenByDescending(p => p.View).Take(8).ToList();
            //ViewBag.Sub = model.GroupBy(p => new { p.SubCategoryId, p.SubCategory.Name }).Select(g => new SubCategory { Id = g.Key.SubCategoryId, Name = g.Key.Name });
            //ViewBag.Ask = db.Questions.Where(q => q.isActive == true).OrderBy(q => q.CreateDate).Take(5).ToList();
            //ViewBag.Article = db.Articles.Where(q => q.isActive == true).OrderBy(q => q.View).Take(8).ToList();
            //return View(model);
            int CurrentId = User.Identity.GetUserId<int>();
        

            List<UserProfile> model = db.UserProfiles.Where(u => u.Id == CurrentId).ToList();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Error()
        {
            return View();
        }
    }
}

HNHN/Controllers/PlaceController.cs
using HNHB.HelperExtension;
using HNHB.Models.Entities;
using FeedFormulation.HelperExtension;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.Data;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Data.Entity;
using HNHB.Models;
using HNHB.DAO;
using System.Device.Location;

namespace HNHB.Controllers
{
    public class PlaceController : Controller
    {
        // GET: Place
        Entities db = new Entities();
        public ActionResult Index(string layoutSearch, int? tag, int? subcategory)
        {
            ViewBag.DistrictId = new SelectList(db.Districts, "Id", "DistrictName");
            if (tag != null)
            {
                ViewBag.TagId = new SelectList(db.Tags, "Id", "Name", tag);
            }
            else
            {
                ViewBag.TagId = new SelectList(db.Tags, "Id", "Name");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            ViewBag.SubCategories = from s in db.SubCategories
                                    where s.isActive == true
                                    select s;
            if (subcategory != null)
            {
                ViewBag.SelectedSub = subcategory;
            }
            if (layoutSearch != null && layoutSearch.Trim().Length > 0)
            {
                layoutSearch = layoutSearch.Trim();
                ViewBag.LayoutSearch = layoutSearch;
            }
            return View();
        }

        public ActionResult GetPlaceList(int? page, string search, string sort, List<int> district, List<int> tag, List<int> subcategory)
        {
            //Prepare paging
            if (page == null)
            {
                page = 1;
            }
            int num = (int)page * 8;
            List<Place> place = db.Places.Where(p => p.IsActive == true).ToList();
            ViewBag.SearchKey = "";
            //Search
            if (search != null && search.Trim().Length > 0)
            {
                ViewBag.SearchKey = search;
                search = search.Trim().ToLower().ToUnsign();
                List<int> placebyitem = new List<int>();
                foreach (var item in db.Items)
                {
                    if (placebyitem.Contains(item.PlaceId))
                        continue;
                    var name = item.Name.ToLower().ToUnsign();
                    if (BreakStringsAndCheck(search, name) >= 50 || name.Contains(search))
                    {
                        placebyitem.Add(item.PlaceId);
                    }
                }
                place = place.Where(p => BreakStringsAndCheck(search, p.Name.ToLower().ToUnsign()) >= 50 || p.Name.ToLower().ToUnsign().Contains(search) || placebyitem.Contains(p.Id)).ToList();
            }
            //District Filter
            if (district != null && district.Count > 0)
            {
                place = place.Where(p => district.Contains(p.DistrictId)).ToList();
                ViewBag.DistrictId = new MultiSelectList(db.Districts, "Id", "DistrictName", district);
            }
            else
            {
                ViewBag.DistrictId = new SelectList(db.Districts, "Id", "DistrictName");
            }
            //SubCategory Filter
            if (subcategory != null && subcategory.Count > 0)
            {
                place = place.Where(p => subcategory.Contains(p.SubCategoryId)).ToList();
                ViewBag.SubCategoryId = new MultiSelectList(db.SubCategories, "Id", "Name", subcategory);
            }
            else
            {
                if (ViewBag.SearchKey == "")
                {
                    List<int> CateList = new List<int> { 1, 2, 8, 10 };
                    place = place.Where(p => CateList.Contains(p.SubCategory.CategoryId)).ToList();
                }
                ViewBag.SubCategoryId = new SelectList(db.SubCategories, "Id", "Name");
            }
            //Tag Filter
            if (tag != null && tag.Count > 0)
            {
                List<int> listId = db.AppliedTagPlaces.Where(a => tag.Contains(a.TagId)).Select(a => a.PlaceId).Distinct().ToList();
                place = place.Where(p => listId.Contains(p.Id)).ToList();
                ViewBag.TagId = new MultiSelectList(db.Tags, "Id", "Name", tag);
            }
            else
            {
                ViewBag.TagId = new SelectList(db.Tags, "Id", "Name");
            }
            ViewBag.NumOfPlace = place.Count;
            ViewBag.Page = page;
            //Sort
            if (sort == null)
            {
                sort = "view";
            }
            switch (sort.ToString())
            {
                case "view": place = place.OrderByDescending(p => p.View).ToList();
                    break;
                case "new": place = place.OrderByDescending(p => p.CreateDate).ToList();
                    break;
                case "rate": place = place.OrderByDescending(p => p.RateValue).ToList();
                    break;
                case "review": place = place.OrderByDescending(p => p.Reviews.Count()).ToList();
                    break;
                case "lowprice": place = place.OrderBy(p => p.Items.FirstOrDefault() != null ? p.Items.FirstOrDefault().Price : double.MaxValue).ToList();
                    break;
            }
            ViewBag.Sort = sort.ToString();
            return PartialView(place.Take(num));
        }

        public JsonResult GetSubCategories(int id)
        {
            var data = from s in db.SubCategories
                       where s.CategoryId == id
                       select new { Id = s.Id, Name = s.Name };
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        //
        // GET: /Place/Create
        [Authorize]
        public ActionResult Create()
        {
            int first = db.Categories.Where(c => c.isActive == true && c.SubCategories.Count > 0).FirstOrDefault().Id;
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            ViewBag.SubCategoryId = new SelectList(db.SubCategories.Where(s => s.CategoryId == first), "Id", "Name");
            ViewBag.DistrictId = new SelectList(db.Districts, "Id", "DistrictName");
            ViewBag.TagId = new SelectList(db.Tags, "Id", "Name");
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(Place model)
        {
            if (ModelState.IsValid)
            {
                model.IsApproved = true;
                //model.IsApproved = false;
                //if (Roles.IsUserInRole(User.Identity.Name, "Administrator"))
                //{
                //    model.IsApproved = true;
                //}
                Place place = new Place()
                {


                    Name = model.Name,
                    Address = model.Address,
                    SubCategoryId = model.SubCategoryId,
                    DistrictId = model.DistrictId,
                    UserId = User.Identity.GetUserId<int>(),
                    PhoneNumber = model.PhoneNumber,
                    Description = model.Description,
                    StartTime = model.StartTime,
                    EndTime = model.EndTime,
                    CreateDate = DateTime.Now,
                    IsActive = true,
                    IsApproved = model.IsApproved,
                    RateValue = 0,
                    View = 0,
                    Virtualtourist = model.Virtualtourist

                };
                db.Places.Add(place);
                db.SaveChanges();
                Coordinate coordinate = CoordinateExtension.GetCoordinates(model.Address);
                if (coordinate != null)
                {
                    coordinate.PlaceId = place.Id;
                    db.Coordinates.Add(coordinate);
                    db.SaveChanges();
                }
                else
                {
                    coordinate = new Coordinate
                    {
                        PlaceId = place.Id,
                        Latitude = 16.0466743,
                        Longitude = 108.206706
                    };
                }
                if (model.SelectedTagIds != null && model.SelectedTagIds.Count > 0)
                {
                    foreach (var tag in model.SelectedTagIds)
                    {
                        AppliedTagPlace appliedTag = new AppliedTagPlace()
                        {
                            PlaceId = place.Id,
                            TagId = tag,
                            AppliedDate = place.CreateDate
                        };
                        db.AppliedTagPlaces.Add(appliedTag);
                    }
                    db.SaveChanges();
                }
                if (model.Items.Count > 0)
                {
                    foreach (var item in model.Items)
                    {
                        Item addedItem = new Item()
                        {
                            Name = item.Name,
                            Price = item.Price,
                            PlaceId = place.Id,
                            isActive = true
                        };
                        db.Items.Add(addedItem);
                    }
                    db.SaveChanges();
                }
                foreach (string fileName in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[fileName];
                    //Save file content goes here
                    List<string> list = ImageUploadExtension.renameUploadFile(file, "Resize");
                    if (list != null)
                    {

HNHN/Views/Home/About.cshtml
@{
    ViewBag.Title = "Về Chúng Tôi";
}
<style>
    .team-five {
        margin: 0;
    }

    .foot {
        margin-top: 0 !important;
    }
</style>
<script type="text/javascript">
    $('.main-block div:first').removeClass('container');
    $('.main-block div:first div:first').removeClass('row');
</script>
<div class="team-five bg-color">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <!-- Team member -->
                <div class="team-member">
                    <!-- Image -->
                    <img class="img-responsive" src="~/Content/img/Team/Linh.jpg" />
                    <!-- Image details -->
                    <div class="team-details">
                        <!-- Name -->
                        <h4>Nguyễn Đinh Ginag Lĩnh</h4>
                        <span class="deg">SE60915</span>
                        <!-- Social -->
                        <div class="brand-bg">
                            <a class="facebook" href="#"><i class="fa fa-facebook circle-3"></i></a>
                            <a class="google-plus" href="#"><i class="fa fa-google-plus circle-3"></i></a>
                            <a class="twitter" href="#"><i class="fa fa-twitter circle-3"></i></a>
                            <a class="linkedin" href="#"><i class="fa fa-linkedin circle-3"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <!-- Team member -->
                <div class="team-member">
                    <!-- Image -->
                    <img class="img-responsive" src="~/Content/img/Team/hai.jpg" />
                    <!-- Image details -->
                    <div class="team-details">
                        <!-- Name -->
                        <h4>Đỗ Hoàng Hải</h4>
                        <span class="deg">SE60663</span>
                        <!-- Social -->
                        <div class="brand-bg">
                            <a class="facebook" href="#"><i class="fa fa-facebook circle-3"></i></a>
                            <a class="google-plus" href="#"><i class="fa fa-google-plus circle-3"></i></a>
                            <a class="twitter" href="#"><i class="fa fa-twitter circle-3"></i></a>
                            <a class="linkedin" href="#"><i class="fa fa-linkedin circle-3"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <!-- Team member -->
                <div class="team-member">
                    <!-- Image -->
                    <img class="img-responsive" src="~/Content/img/Team/Tien.jpg" />
                    <!-- Image details -->
                    <div class="team-details">
                        <!-- Name -->
                        <h4>Vũ Nguyên Việt Tiến</h4>
                        <span class="deg">SE61121</span>
                        <!-- Social -->
                        <div class="brand-bg">
                            <a class="facebook" href="#"><i class="fa fa-facebook circle-3"></i></a>
                            <a class="google-plus" href="#"><i class="fa fa-google-plus circle-3"></i></a>
                            <a class="twitter" href="#"><i class="fa fa-twitter circle-3"></i></a>
                            <a class="linkedin" href="#"><i class="fa fa-linkedin circle-3"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-sm-6">
                <!-- Team member -->
                <div class="team-member">
                    <!-- Image -->
                    <img class="img-responsive" src="~/Content/img/Team/Cuong.jpg" />
                    <!-- Image details -->
                    <div class="team-details">
                        <!-- Name -->
                        <h4>Nguyễn Lê Tuấn Cường</h4>
                        <span class="deg">SE02789</span>
                        <!-- Social -->
                        <div class="brand-bg">
                            <a class="facebook" href="#"><i class="fa fa-facebook circle-3"></i></a>
                            <a class="google-plus" href="#"><i class="fa fa-google-plus circle-3"></i></a>
                            <a class="twitter" href="#"><i class="fa fa-twitter circle-3"></i></a>
                            <a class="linkedin" href="#"><i class="fa fa-linkedin circle-3"></i></a>
                        </div>
                    </div>
                </div>
            </div>
           
           
        </div>
    </div>
</div>

HNHN/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HNHN/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
}
@model HNHB.Models.Entities.UserProfile
@using Microsoft.AspNet.Identity
@using System.Text.RegularExpressions
@using HNHB.HelperExtension

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Hà Nội Handbook";
}

<link href="~/Content/themes/brave/css/styles/parallax.css" rel="stylesheet" />
<style>
    .main-pic-thumb {
        height: 250px;
        border-radius: 3px;
        background-position: center center;
        background-size: cover;
    }
</style>
<script type="text/javascript">
    $('.main-block div:first').removeClass('container');
    $('.main-block div:first div:first').removeClass('row');
</script>
<div id="bs-carousel-2" class="carousel slide" data-ride="carousel" data-interval="3000" data-pause="hover" data-wrap="true" style="margin: 0px auto">
    <!-- Bootstrap indicators. If you don't need indicators, remove the below section -->
    <ol class="carousel-indicators">
        <li data-target="#bs-carousel-2" data-slide-to="0" class="active"></li>
        <li data-target="#bs-carousel-2" data-slide-to="1"></li>
        <li data-target="#bs-carousel-2" data-slide-to="2"></li>
        <li data-target="#bs-carousel-2" data-slide-to="3"></li>
        <li data-target="#bs-carousel-2" data-slide-to="4"></li>
    </ol>
 
    @*<div class="col-md-3 col-sm-4 col-xs-4">
         Image 
        @if (Model.Avatar != null)
        {
            <img src="@Url.Content(Model.Avatar)" class="img-responsive img-thumbnail" alt="">
        }
        else
        {
            <img src="@Url.Content("~/Content/img/non-avatar.png")" class="img-responsive img-thumbnail" alt="">
        }
    </div>*@

    <!-- Slides. You can also add captions -->
    <header>
        <!--Start of Zopim Live Chat Script-->
        <!--Start of Zopim Live Chat Script-->
        <script type="text/javascript">
            window.$zopim || (function (d, s) {
                var z = $zopim = function (c) { z._.push(c) }, $ = z.s =
                d.createElement(s), e = d.getElementsByTagName(s)[0]; z.set = function (o) {
                    z.set.
                    _.push(o)
                }; z._ = []; z.set._ = []; $.async = !0; $.setAttribute("charset", "utf-8");
                $.src = "//v2.zopim.com/?3QEydufhF52xklTX7Ed5u9oUViH2GMsC"; z.t = +new Date; $.
                type = "text/javascript"; e.parentNode.insertBefore($, e)
            })(document, "script");
        </script>
        <!--End of Zopim Live Chat Script-->
        <script type="text/javascript">
$zopim(function () {
    $zopim.livechat.setLanguage('ja');
});</script>
     
    </header>
    <div class="carousel-inner">
        <!-- Item, First item should have extra class "active" -->
        <div class="item active">
            <!-- Image -->
            <img src="/Content/img/home/slider/1.jpg" style="width:100%" />
            <!-- Caption -->
            <div class="carousel-caption c-bottom-right">
                <!-- Heading -->
                <h4><a href="#">Hà Nội về đêm</a></h4>
                <!-- Para -->
                <p>Hồ Gươm về đêm.</p>
            </div>
        </div>
        <div class="item">
            <img src="/Content/img/home/slider/2.jpg" style="width:100%" />
            <div class="carousel-caption c-bottom-right">
                <!-- Heading -->
                <h4><a href="#">Cầu Nhật Lệ</a></h4>
                <!-- Para -->
                <p>Cầu Nhật Lệ, Cây cầu lớn nhất Hà Nội, bắc ngang qua sông Hồng</p>
            </div>
        </div>
        <div class="item">
            <img src="/Content/img/home/slider/3.jpg" style="width:100%" />
            <div class="carousel-caption c-bottom-right">
                <!-- Heading -->
                <h4><a href="#">Cầu Long Biên</a></h4>
                <!-- Para -->
                <p>Cầu Long Biên là cây cầu thép đầu tiên bắc qua sông Hồng nối hai quận Hoàn Kiếm với quận Long Biên của Hà Nội, do Pháp xây dựng (1898-1902), đặt tên là cầu Doumer, theo tên của Toàn quyền Đông Dương Paul Doumer. Dân gian còn gọi là cầu sông Cái hay cầu Bồ Đề (vì nó được bắt qua bến Bồ Đề thuộc huyện Gia Lâm). Hiện trên đầu cầu vẫn còn tấm biển kim loại có khắc chữ 1899 -1902 - Daydé & Pillé - Paris.</p>
            </div>
        </div>
        <div class="item">
            <img src="/Content/img/home/slider/4.jpg" style="width:100%" />
            <div class="carousel-caption c-bottom-right">
                <!-- Heading -->
                <h4><a href="#">Hồ Tây</a></h4>
                <!-- Para -->
                <p>Hồ Tây trước đây còn có các tên gọi khác như Đầm Xác Cáo, Hồ Kim Ngưu, Lãng Bạc, Dâm Đàm, Đoài Hồ, là một hồ nước tự nhiên lớn nhất ở nội thành Hà Nội. Hồ có diện tích hơn 500 ha với chu vi là 18 km [2]. Hồ nằm ở vị trí phía tây bắc trung tâm Hà Nội. Ngành địa lý lịch sử đã chứng minh, hồ Tây là một đoạn của sông Hồng xưa trong quá trình ngưng đọng lại sau khi sông đổi dòng chảy[3]. Các khu vực liền kề xung quanh hồ Tây sẽ được quy hoạch để trở thành trung tâm của Thủ đô Hà Nội mới trong tương lai gần. Thay thế dần vị trí hiện nay đang là Hồ Hoàn Kiếm.</p>
            </div>
        </div>
        <div class="item">
            <img src="/Content/img/home/slider/5.jpg" style="width:100%" />
            <div class="carousel-caption c-bottom-right">
                <!-- Heading -->
                <h4><a href="#">Văn Miếu</a></h4>
                <!-- Para -->
                <p>Văn Miếu – Quốc Tử Giám(chữ Hán: 文廟 – 國子監) là quần thể di tích đa dạng và phong phú hàng đầu của thành phố Hà Nội, nằm ở phía Nam kinh thành Thăng Long. Hiện nay, nơi đây đã được thủ tướng chính phủ Việt Nam đưa vào danh sách xếp hạng 23 di tích quốc gia đặc biệt. Quần thể kiến trúc Văn Miếu - Quốc Tử Giám bao gồm: hồ Văn, khu Văn Miếu - Quốc Tử Giám và vườn Giám và kiến trúc chủ thể là Văn Miếu - nơi thờ Khổng Tử và Quốc Tử Giám - trường đại học đầu tiên của Việt Nam.</p>
            </div>
        </div>
    </div>
    <!-- Carousel controls (arrows). If you don't need controls, remove the below section -->
    <a class="left carousel-control" href="#bs-carousel-2" role="button" data-slide="prev">
        <span class="fa fa-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#bs-carousel-2" role="button" data-slide="next">
        <span class="fa fa-chevron-right"></span>
    </a>
</div>
<div class="parallax-three bg-white">
    <div class="container">
        <!-- Parallax text element block -->
        <div class="p-element">
            <!-- Heading -->
            <h2>Hà Nội</h2>
            <h3>Thủ đô Việt Nam</h3>
            <a class="btn btn-blue" href="@Url.Action("About", "Home")">Thông tin về chúng tôi</a>
        </div>
    </div>
</div>
<div class="parallax-four" style="background-image:url('../../Content/img/home/1.jpg');padding:70px 0px 30px 0px">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <!-- Parallax text element block -->
                <div class="p-element">
                    <!-- Heading -->
                    <center><h2>Những địa điểm tuyệt vời</h2></center>
                </div>
            </div>
            <div>
                <div class="index-portfolio">
                    <!-- Portfolio Start -->
                    <div class="portfolio pf-one">
                        <!-- Portfolio Block Content -->
                       
                        </div>
                    </div>
                    <!-- Portfolio End -->
                </div>
            </div>
            <center style="margin-top:20px">
                <a class="btn btn-green" href="@Url.Action("Index", "Place")">Xem các địa điểm khác</a>
            </center>
        </div>
    </div>

<div class="parallax-four" style="background-color:#FFF;background-image:none;padding:70px 0px 30px 0px">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <!-- Parallax text element block -->
                <div class="p-element">
                    <!-- Heading -->
                    <center><h2 style="color:#555;text-shadow:none">Hỏi đáp về Hà Nội</h2></center>
                </div>
            </div>
            <div class="col-md-12 col-sm-12">
                <!-- Testimonial with carousel -->
                <div class="testimonials-one">
                    <!-- Navigation -->
                    <div class="owl-nav">
                        <a class="owl-nav-prev"><i class="fa fa-chevron-left"></i></a>
                        <a class="owl-nav-next"><i class="fa fa-chevron-right"></i></a>
                    </div>
                    <div class="owl-carousel" data-items="3" data-auto-play="true" data-pagination="false" data-single-item="false">
                     
                    </div>
                </div>
            </div>
        </div>
        <center style="margin-top:30px">
            <a class="btn btn-green" href="@Url.Action("Index", "Asking")">Xem các câu hỏi khác</a>
        </center>
    </div>
</div>
<div class="parallax-four" style="background-image:url('../../Content/img/home/2.jpg');padding:70px 0px 30px 0px">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <!-- Parallax text element block -->
                <div class="p-element">
                    <!-- Heading -->
                    <center><h2>Những bài viết về Hà Nội</h2></center>
                </div>
            </div>
        
        </div>
        <center style="margin-top:30px">
            <a class="btn btn-green" href="@Url.Action("Index", "Article")">Xem các bài viết khác</a>
        </center>
    </div>
</div>
<div class="parallax-four" style="background-color:#FFF;background-image:none;padding:70px 0px 30px 0px">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <!-- Parallax text element block -->
                <div class="p-element">
                    <!-- Heading -->
                    <center><h2 style="color:#555;text-shadow:none">Sự kiện nổi bật</h2></center>
                </div>
            </div>
            <div class="col-md-12 col-sm-12">
                @Html.Partial("~/Views/Calendar/PatialCalendar.cshtml")
            </div>
        </div>
    </div>
   
</div>
<!-- Place this tag where you want the Live Helper Plugin to render. -->
<div id="lhc_status_container_page"></div>

<!-- Place this tag after the Live Helper Plugin tag. -->
<script type="text/javascript">
    var zochatOptionsPage = {};
    zochatOptionsPage.opt = {};
    (function () {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://linhndg.zochat.net/eng/chat/getstatusembed';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();
</script>
<!-- Imageloaded -->
<script src="~/Content/themes/brave/js/imagesloaded.min.js"></script>
<!-- Isotope -->
<script src="~/Content/themes/brave/js/isotope.js"></script>
<script type="text/javascript">
    var $container = $('#portfolio');

    // Initialize isotope
    $container.imagesLoaded(function () {
        $container.fadeIn(1000).isotope({
            layoutMode: 'fitRows',
            itemSelector: '.p-element'
        });
    });

    // Filter items when filter link is clicked

    $('#filters a').click(function () {
        var selector = $(this).attr('data-filter');
        $container.isotope({ filter: selector });
        return false;
    });
</script>

HNHN/Views/Home/IndexDemo.cshtml
@{
    ViewBag.Title = "IndexDemo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>IndexDemo</h2>