HNHN/Controllers/AskingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HNHB.Models;
using System.Data.Entity;
using Newtonsoft.Json;
using HNHB.HelperExtension;
using System.Data;
using HNHB.Models.Entities;
using HNHB.DAO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Text;
using System.Net;
using System.IO;


namespace HNHB.Controllers
{
    
    
    public class AskingController : Controller
    {
        // Get database
        Entities db = new Entities();
        AskingDAO AskingDAO = new AskingDAO();
        // GET: Asking
        //const string APIKey = "411DA00A2AF749AD511C405870AE43";
        //const string SecretKey = "FB0E24FEA02BFAF407EBDB51CD12AD";
        public ActionResult Index(int? tagId, string key)
        {
            var question = AskingDAO.ListQuestion();
            ViewBag.lstByView = AskingDAO.LstByView().Take(7);
            ViewBag.lstByDate = AskingDAO.LstByDate().Take(7);
            ViewBag.lstByAnswer = (from v in db.Answers where v.Question.isActive == true && v.isActive == true select v)
                            .ToList().OrderByDescending(v => v.CreateDate).Take(7);
            List<int> allTgs = AskingDAO.LstAllTag();
            if (tagId != null)
            {
                List<int> listId = db.AppliedTagQuestions.Where(a => a.TagId == tagId).Select(a => a.QuestionId).Distinct().ToList();
                question = question.Where(q => listId.Contains(q.Id)).ToList();
            }
            if (key != null)
            {
                question = question.Where(q => q.Title.ToLower().ConvertToUnSign().Contains(key.ToLower().ConvertToUnSign())).ToList();
                ViewBag.Key = key;
            }
            ViewBag.allTags = db.Tags.Where(t => allTgs.Contains(t.Id));
            return View(question);
        }

        [Authorize]
        public ActionResult CreateQuestion()
        {
            var lstTags = (from tag in db.Tags select tag).ToList();
            return View(lstTags);
        }
        // Create Question
        [Authorize]
        [HttpPost, ValidateInput(false)]
        public ActionResult CreateQuestion(string editorContent, string tagSelect, string stringTitle)
        {
            var appliedTagList = JsonConvert.DeserializeObject<string[]>(tagSelect);
            int ptId = 0;
            if (ModelState.IsValid)
            {
                Question asking = new Question();

                asking.Title = stringTitle;
                while (editorContent.EndsWith("<br>"))
                    editorContent = editorContent.Substring(0, editorContent.Length - 4);
                asking.Content = editorContent.Trim('\r', '\n', ' ');
                //article.UserId =  User.Identity.GetUserId<int>();
                asking.UserId =  User.Identity.GetUserId<int>();
                asking.CreateDate = DateTime.Now;
                asking.isActive = true;
                //asking. = 0;

                db.Questions.Add(asking);
                db.SaveChanges();
                ptId = asking.Id;
                if (appliedTagList != null)
                {
                    foreach (var item in appliedTagList)
                    {
                        AppliedTagQuestion appliedTag = new AppliedTagQuestion();
                        appliedTag.QuestionId = asking.Id;
                        appliedTag.TagId = Int32.Parse(item);
                        //appliedTag.TaggingUser =  User.Identity.GetUserId<int>();
                        appliedTag.AppliedDate = DateTime.Now;
                        db.AppliedTagQuestions.Add(appliedTag);
                        db.SaveChanges();
                    }
                }
            }
          
            return Json(ptId, JsonRequestBehavior.AllowGet);
        }
     // View Detail of question
        public ActionResult QuestionDetails(int? id = 0)
        {
            if (id == 0)
            {
                return RedirectToAction("Error", "Home");
            }

            var questionContent = (from qtContent in db.Questions
                                   where qtContent.Id == id && qtContent.isActive == true
                                   select qtContent).Single();
            Question qt = questionContent;
            qt.View++;
            db.SaveChanges();
            ViewBag.lstByView = (from v in db.Questions where v.isActive == true select v)
                .ToList().OrderByDescending(v => v.View).Take(7);
            ViewBag.lstByDate = (from v in db.Questions where v.isActive == true select v)
                .ToList().OrderByDescending(v => v.CreateDate).Take(7);
            ViewBag.lstByAnswer = (from v in db.Answers where v.Question.isActive == true && v.isActive == true select v)
                            .ToList().OrderByDescending(v => v.CreateDate).Take(7);
            List<int> allTgs = db.AppliedTagQuestions.GroupBy(a => a.TagId).OrderBy(g => g.Count()).Select(g => g.Key).ToList();

            ViewBag.allTags = db.Tags.Where(t => allTgs.Contains(t.Id));

            return View(questionContent);
        }
        // Post answer 
        [Authorize]
        public ActionResult AnswerQuestion(string qtContent, int qtId = 0)
        {
            if (ModelState.IsValid)
            {
                Answer ans = new Answer();
                ans.QuestionId = qtId;
                ans.Content = qtContent;
                ans.UserId =  User.Identity.GetUserId<int>();
                ans.CreateDate = DateTime.Now;
                ans.isActive = true;

                db.Answers.Add(ans);
                db.SaveChanges();
            }


            var answer = (from ans in db.Answers.Include("UserProfile")
                          where ans.QuestionId == qtId && ans.isActive == true
                          select ans).ToList().OrderByDescending(x => x.CreateDate);
            return PartialView("QtAnswerPartial", answer);
        }
        // Delete answer by admin
        [Authorize(Roles = "Administrator")]
        public ActionResult RemoveAnswer(int ansId)
        {
            Answer ans = db.Answers.Find(ansId);
            if (ans != null)
            {
                ans.isActive = false;
                db.Entry(ans).State = EntityState.Modified;
                db.SaveChanges();
            }
            var answer = (from a in db.Answers.Include("UserProfile")
                          where a.QuestionId == ans.QuestionId && a.isActive == true
                          select a).ToList().OrderByDescending(x => x.CreateDate);
            return PartialView("QtAnswerPartial", answer);
        }
        // Vote up function
        [HttpGet]
        [Authorize]
        public ActionResult VoteUp(int? canswerId)
        {
            if (ModelState.IsValid)
            {
                Vote vt = new Vote();
                vt.AnswerId = canswerId;
                vt.Value = 1;
                vt.UserId =  User.Identity.GetUserId<int>();

                db.Votes.Add(vt);
                db.SaveChanges();
            }

            var votes = (from v in db.Votes where v.AnswerId == canswerId select v).Sum(x => x.Value);

            return Json(votes, JsonRequestBehavior.AllowGet);
        }
        // Vote down function
        [Authorize]
        [HttpGet]
        [Authorize]
        public ActionResult VoteDown(int? canswerId)
        {
            int userId =  User.Identity.GetUserId<int>();
            if (ModelState.IsValid)
            {
                Vote vt = new Vote();
                vt.AnswerId = canswerId;
                vt.Value = -1;
                vt.UserId = userId;

                db.Votes.Add(vt);
                db.SaveChanges();
            }

            var votes = (from v in db.Votes where v.AnswerId == canswerId select v).Sum(x => x.Value);

            return Json(votes, JsonRequestBehavior.AllowGet);
        }

        private double BreakStringsAndCheck(string s1, string s2)
        {
            if (s1.Length > s2.Length)
            {
                var tmp = s2;
                s2 = s1;
                s1 = tmp;
            }
            var split1 = s1.Split(' ');
            return (double)split1.Intersect(s2.Split(' ')).Count() / split1.Count() * 100.0;
        }
        // Get list to suggest Anwer
        [HttpPost]
        public ActionResult QuestionSuggest(string title)
        {
            List<Question> results = new List<Question>();
            foreach (var question in db.Questions.Where(q => q.isActive == true && q.Answers.Count > 0))
            {
                if (BreakStringsAndCheck(title.ToLower().ToUnsign(), question.Title.ToLower().ToUnsign()) >= 50)
                {
                    Question result = new Question
                    {
                        Id = question.Id,
                        Title = question.Title,
                        Content = question.Answers.Count + " câu trả lời, " + question.CreateDate.ToTimeAgo()
                    };
                    results.Add(result);
                }
            }
            if (results.Count > 0)
            {
                return Json(new { success = true, result = results });
            }
            return Json(new { success = false });
        }
        // Return vote for answer
        [Authorize]
        [HttpGet]
        public ActionResult CurrentUserVote(int? canswerId)
        {
            var isVote = (from v in db.Votes
                          where v.AnswerId == canswerId
                              && v.UserProfile.UserName == User.Identity.Name
                          select v).Sum(x => x.Value);
            return Json(isVote, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult EditQuestion(int? id)
        {

HNHN/Views/Asking/Index.cshtml
@model IEnumerable<HNHB.Models.Entities.Question>
@using System.Text.RegularExpressions
@using HNHB.HelperExtension
@{
    ViewBag.Title = "Hỏi Đáp";
}
<link href="~/Content/themes/brave/css/styles/real-estate.css" rel="stylesheet" />
<div class="col-md-8">
    <div class="rs-agency">
        <!-- Real estate agency details -->
        @foreach (var item in Model)
        {
            var urlTitle = item.Title.ConvertToUnSign();
            if (urlTitle.Length > 150)
            {
                urlTitle = urlTitle.Substring(0, 150);
            }
            <div class="agency-item">
                <!-- Name -->
                <h4><a href="@Url.Action("QuestionDetails", "Asking", new { id = item.Id, title = urlTitle })">@item.Title</a></h4>
                <!-- Contact details -->
                <span class="agency-contact"><i class="fa fa-calendar circle-2 bg-red"></i>&nbsp; @item.CreateDate.ToTimeAgo()</span> &nbsp;
                <span class="agency-contact"><i class="fa fa-user circle-2 bg-blue"></i>&nbsp; @item.UserProfile.Fullname</span> &nbsp;
                <span class="agency-contact"><i class="fa fa-comments circle-2 bg-green"></i>&nbsp; @item.Answers.Count() Trả lời</span>
                @{

            string text = item.Content;
            Regex reg = new Regex(@"</?img((\s+\w+(\s*=\s*(?:"".*?""|\'.*?\'|[^\'"">\s]+))?)+\s*|\s*)/?>");
            string result = reg.Replace(text, string.Empty);
            result = Regex.Replace(result, "<.*?>", string.Empty);
            <p style="word-wrap: break-word;">@Html.Raw(HttpUtility.HtmlDecode(Html.GetSummary(result, 100) + "..."))</p>
                }
            </div>
        }
    </div>
</div>
<div class="col-md-4">

    <!-- Take action sidebar block -->
    <div class="sidebar">

        <!-- Search Widget -->
        <div class="s-widget">
            <!-- Heading -->
            <h5><i class="fa fa-search color"></i>&nbsp; Tìm kiếm</h5>
            <!-- Widgets Content -->
            <div class="widget-content search">
                @using (Html.BeginForm("Index", "Asking"))
                {
                    <div class="input-group">
                        <input class="form-control" type="text" id="txtSearch" name="key" value="@ViewBag.Key">
                        <span class="input-group-btn">
                            <button class="btn btn-color" type="submit">Tìm kiếm</button>
                        </span>
                    </div>
                }
            </div>
        </div>
        <div class="s-widget">
            <!-- Heading -->
            <h5><i class="fa fa-question color"></i>&nbsp; Câu hỏi</h5>
            <!-- Widgets Content -->
            <div class="widget-content tabs">
                <a class="btn btn-sm  btn-lblue" style="width:100%" href="@Url.Action("CreateQuestion", "Asking")">Câu hỏi mới</a>
                <div class="nav-tabs-two" style="margin-top:10px">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#popular" data-toggle="tab">Xem nhiều</a></li>
                        <li><a href="#recent" data-toggle="tab">Mới nhất</a></li>
                        <li><a href="#comments" data-toggle="tab">Trả lời mới</a></li>
                    </ul>
                    <!-- Tab content -->
                    <div class="tab-content">
                        <!-- Popular posts -->
                        <div class="tab-pane fade in active" id="popular">
                            <ul>
                                @foreach (var item in ViewBag.lstByView)
                                {
                                    string urlTitle = item.Title;
                                    urlTitle = urlTitle.ConvertToUnSign();
                                    if (urlTitle.Length > 150)
                                    {
                                        urlTitle = urlTitle.Substring(0, 150);
                                    }
                                    <li>
                                        <a href="@Url.Action("QuestionDetails", "Asking", new { id = item.Id, title = urlTitle })">
                                            <!-- Item title -->
                                            @{
                                    string tit = item.Title;
                                    if (tit.Length > 43)
                                    {
                                        <strong title="@tit">@tit.Substring(0, 40)<text>...</text></strong>
                                    }
                                    else
                                    {
                                        <strong>@tit</strong>
                                    }
                                            }
                                            <div class="agency-item row">
                                                @{
                                    DateTime date = item.CreateDate;
                                    <div class="col-md-6">
                                        <span class="agency-contact"><i class="fa fa-calendar circle-2 bg-red white"></i>&nbsp; @date.ToTimeAgo() &nbsp;</span>
                                    </div>
                                                    <div class="col-md-6">
                                                        <span class="agency-contact"><i class="fa fa-eye circle-2 bg-yellow white"></i>&nbsp; @item.View Lượt xem</span>
                                                    </div>
                                                }
                                            </div>
                                            <div class="clearfix"></div>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </div>
                        <!-- Recent posts -->
                        <div class="tab-pane fade" id="recent">
                            <ul>
                                @foreach (var item in ViewBag.lstByDate)
                                {
                                    string urlTitle = item.Title;
                                    urlTitle = urlTitle.ConvertToUnSign();
                                    if (urlTitle.Length > 150)
                                    {
                                        urlTitle = urlTitle.Substring(0, 150);
                                    }
                                    <li>
                                        <a href="@Url.Action("QuestionDetails", "Asking", new { id = item.Id, title = urlTitle })">
                                            <!-- Item title -->
                                            @{
                                    string tit = item.Title;
                                    if (tit.Length > 43)
                                    {
                                        <strong title="@tit">@tit.Substring(0, 40)<text>...</text></strong>
                                    }
                                    else
                                    {
                                        <strong>@tit</strong>
                                    }
                                            }
                                            <div class="agency-item row">
                                                @{
                                    DateTime date = item.CreateDate;
                                    <div class="col-md-6">
                                        <span class="agency-contact"><i class="fa fa-calendar circle-2 bg-red white"></i>&nbsp; @date.ToTimeAgo() &nbsp;</span>
                                    </div>
                                                    <div class="col-md-6">
                                                        <span class="agency-contact"><i class="fa fa-comments circle-2 bg-green white"></i>&nbsp; @item.Answers.Count Trả lời</span>
                                                    </div>
                                                }
                                            </div>
                                            <div class="clearfix"></div>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </div>
                        <!-- Recent comments -->
                        <div class="tab-pane fade" id="comments">
                            <ul>
                                @foreach (var item in ViewBag.lstByAnswer)
                                {
                                    string urlTitle = item.Question.Title;
                                    urlTitle = urlTitle.ConvertToUnSign();
                                    if (urlTitle.Length > 150)
                                    {
                                        urlTitle = urlTitle.Substring(0, 150);
                                    }
                                    <li>
                                        <a href="@Url.Action("QuestionDetails", "Asking", new { id = item.QuestionId, title = urlTitle })">
                                            @{
                                    string text = item.Content;
                                    Regex reg = new Regex(@"</?img((\s+\w+(\s*=\s*(?:"".*?""|\'.*?\'|[^\'"">\s]+))?)+\s*|\s*)/?>");
                                    string result = reg.Replace(text, string.Empty);
                                    <span>@Html.Raw(HttpUtility.HtmlDecode(Html.GetSummary(result, 80) + "..."))</span>
                                            }
                                            <div class="agency-item">
                                                <span class="agency-contact">
                                                    <i class="fa fa-question circle-2 bg-blue white"></i>
                                                </span>
                                                @{
                                    string tit = item.Question.Title;
                                    if (tit.Length > 43)
                                    {
                                        <strong title="@tit">@tit.Substring(0, 40)<text>...</text></strong>
                                    }
                                    else
                                    {
                                        <strong>@tit</strong>
                                    }
                                                }
                                            </div>
                                            <div class="clearfix"></div>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="s-widget">
            <!-- Heading -->
            <h5><i class="fa fa-tags color"></i>&nbsp; Tags</h5>
            <!-- Widgets Content -->
            <div class="widget-content">
                @foreach (var item in ViewBag.allTags)
                {
                    <a href="@Url.Action("Index", "Asking", new { tagId = item.Id })"><span class="label label-lblue">@item.Name</span></a>
                }
            </div>
        </div>
        <!-- Social media widget -->
        <div class="s-widget">
            <h5><i class="fa fa-share color"></i>&nbsp; Chia sẻ</h5>
            <!-- Widgets Content -->
            <div class="widget-content brand-bg">
                <!-- Social Media Icons -->
                <a href="#" class="facebook"><i class="fa fa-facebook square-3 rounded-1"></i></a>
                <a href="#" class="google-plus"><i class="fa fa-google-plus square-3 rounded-1"></i></a>
                
            </div>
        </div>
    </div>
</div>

HNHN/Views/Asking/QtAnswerPartial.cshtml
@model IEnumerable<HNHB.Models.Entities.Answer>
@using HNHB.HelperExtension

<h4><i class="fa fa-comments color"></i>&nbsp; @Model.Count() câu trả lời</h4>
<hr />

@if (Model.Count() == 0)
{
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <strong>Chưa có câu trả lời!</strong> Hãy trở thành người đầu tiên trả lời câu hỏi. Cám ơn sự đóng góp của bạn.
    </div>
}
else
{
    foreach (var item in Model)
    {
        <div class="blog-comment-item" id="@item.Id">
            <div class="comment-author-image">
                @if (item.UserProfile.Avatar != null)
                {
                    <img alt="avatar" class="user" src="@Url.Content(item.UserProfile.Avatar)" style="max-width:60px;border-radius:5px" />
                }
                else
                {
                    <img alt="avatar" class="user" src="@Url.Content("~/Content/img/non-avatar.png")" style="max-width:60px;border-radius:5px" />
                }
            </div>
            <div class="comment-details">
                <!-- Name -->
                <h5>
                    @if (User.Identity.IsAuthenticated == true && User.IsInRole("Administrator"))
                    {
                        using (Ajax.BeginForm("RemoveAnswer", "Asking", new AjaxOptions()
                            {
                                InsertionMode = InsertionMode.Replace,
                                HttpMethod = "Post",
                                UpdateTargetId = "aranswer",
                                OnSuccess = "updateNumOfAns"
                            }, new { @class = "form", role = "form" }))
                        {
                            <input type="hidden" name="ansId" value="@item.Id" />
                            <button class="close red" type="submit" style="opacity:1" title="Xóa câu trả lời">×</button>
                        }
                    }
                    @item.UserProfile.Fullname <small>@item.CreateDate.ToTimeAgo()</small>
                </h5>
                <!-- Paragraph -->
                <p style="word-wrap: break-word;">@item.Content</p>
                @if (User.Identity.IsAuthenticated)
                {
                    var isVote = (from v in item.Votes
                                  where v.AnswerId == item.Id
                                      && v.UserProfile.UserName == User.Identity.Name
                                  select v).Sum(x => x.Value);
                    <p>
                        @if (isVote > 0)
                        {
                            <span title="Đánh giá cao" class="vote-up" id="aVoteUp_@item.Id" role="button" onclick="null" style="cursor:pointer">
                                <span class="control">
                                    <i class="fa fa-chevron-up" aria-hidden="true"></i>
                                </span>
                            </span>
                        }
                        else
                        {
                            <span title="Đánh giá cao" class="vote-up" id="aVoteUp_@item.Id" role="button" onclick="voteup(@item.Id)" style="cursor:pointer">
                                <span class="control">
                                    <i class="fa fa-chevron-up" aria-hidden="true"></i>
                                </span>
                            </span>
                        }


                        @{
                    var votes = (from v in item.Votes where v.AnswerId == item.Id select v).Sum(x => x.Value);
                    <span id="voteValues_@item.Id" data-role="likes" resource="@item.Id" class="updatable count blue">@votes</span>
                        }

                        @if (isVote < 0)
                        {
                            <span id="aVoteDown_@item.Id" title="Đánh giá thấp" class="vote-down" role="button" onclick="null" style="cursor:pointer">
                                <span class="control">
                                    <i class="fa fa-chevron-down" aria-hidden="true"></i>
                                </span>
                            </span>
                        }
                        else
                        {
                            <span id="aVoteDown_@item.Id" title="Đánh giá thấp" class="vote-down" role="button" onclick="votedown(@item.Id)" style="cursor:pointer">
                                <span class="control">
                                    <i class="fa fa-chevron-down" aria-hidden="true"></i>
                                </span>
                            </span>
                        }
                    </p>
                }
                else
                {
                    <p>
                        <span title="Đánh giá cao" class="vote-up" id="aVoteUp" role="button" style="cursor:pointer">
                            <span class="control">
                                <i class="fa fa-chevron-up" aria-hidden="true"></i>
                            </span>
                        </span>
                        @{
                    var votes = (from v in item.Votes where v.AnswerId == item.Id select v).Sum(x => x.Value);
                    <span id="voteValues_@item.Id" data-role="likes" resource="@item.Id" class="updatable count blue">@votes</span>
                        }
                        <span title="Đánh giá thấp" class="vote-down" role="button" style="cursor:pointer">
                            <span class="control">
                                <i class="fa fa-chevron-down" aria-hidden="true"></i>
                            </span>
                        </span>
                    </p>
                }
            </div>
        </div>
    }
}
@if (User.Identity.IsAuthenticated)
{
    <script>
    var isVoting = false;
    function voteup(_id) {
        if (!isVoting) {
            isVoting = true;
            //$('#voteValues').text('100');
            var votes = $('#voteValues_' + _id);
            var asnId = $('#answer_' + _id);
            var answerId = {
                canswerId: _id
                //stringCateId: $(ArCateId).val()
            };
            $.ajax({
                url: "@Url.Action("VoteUp", "Asking")",
                data: answerId,
                type: "GET",
                dataType: "json",
                async: false,
                success: function (result) {
                    votes.text(result);
                    //$('#voteValues').text('100');
                },
                error: function (xhr, status) {
                    votes.text('-10');
                    //alert("Sorry, there was a problem!");
                },
                complete: function (xhr, status) {
                    currentVote(_id);
                }
            });
        }
    };

    function votedown(_id) {
        if (!isVoting) {
            isVoting = true;
            //$('#voteValues').text('100');
            var votes = $('#voteValues_' + _id);
            var asnId = $('#answer_' + _id);
            var answerId = {
                canswerId: _id
                //stringCateId: $(ArCateId).val()
            };
            $.ajax({
                url: "@Url.Action("VoteDown", "Asking")",
                data: answerId,
                type: "GET",
                dataType: "json",
                async: false,
                success: function (result) {
                    votes.text(result);
                    //$('#voteValues').text('100');
                },
                error: function (xhr, status) {
                    //votes.text('-10');
                    //alert("Sorry, there was a problem!");
                },
                complete: function (xhr, status) {
                    currentVote(_id);
                }
            });
        }
    };

    function currentVote(_id) {
        var answerId = {
            canswerId: _id
        };
        $.ajax({
            url: "@Url.Action("CurrentUserVote", "Asking")",
                data: answerId,
                type: "GET",
                dataType: "json",
                success: function (result) {
                    isDisable(_id, result);
                },
                error: function (xhr, status) {
                    isDisable(_id, result);
                },
                complete: function (xhr, status) {
                    isDisable(_id, result);
                }
            });
        };


        function isDisable(id, vote) {
            var svoteup = document.getElementById("aVoteUp_" + id);
            var svotedown = document.getElementById("aVoteDown_" + id);
            var doVoteUp = function () {
                voteup(id);
            };
            var doVoteDown = function () {
                votedown(id);
            };

            if (vote > 0) {
                //voteup.setAttribute("disabled", "disabled");
                //votedown.removeAttribute("disabled");
                svoteup.onclick = null;
                svotedown.onclick = doVoteDown;
            } else if (vote < 0) {
                //voteup.removeAttribute("disabled");
                //votedown.setAttribute("disabled", "disabled");
                svotedown.onclick = null;
                svoteup.onclick = doVoteUp;
            }
            else {
                svoteup.onclick = doVoteUp;
                svotedown.onclick = doVoteDown;
            }
            isVoting = false;
        };
    </script>


}